#
# $ZDOTDIR/.zshenv
#
listop prepend PROFILES ${(%):-%x}

# tmux colors
# TODO: import these settings from host-specific env files
export TMUX_STATUS_BG="black"

# go
export GOPATH=$XDG_DATA_HOME/go
export PATH=$GOPATH/bin:$PATH
typeset -U path
# Android SDK
export ANDROID_HOME=$XDG_DATA_HOME/android/sdk
export JAVA_HOME=/usr/lib/jvm/default

# steam
export STEAM_RUNTIME=0

hostenv=$XDG_CONFIG_HOME/zsh/zshenv.$HOST
hostenvd=$XDG_CONFIG_HOME/zsh/zshenv.${HOST}.d
[ -f "$hostenv" ] && source "$hostenv"
[ -e "$hostenvd" ] && for f (~/**/*(N.)); do
  source "$hostenvd"/**/*
done
