#!/usr/bin/env zsh
#
# $ZDOTDIR/.zshrc
#
# This file contains configuration for zsh
#
# Lines configured by zsh-newuser-install
# shell history
listop prepend PROFILES ${(%):-%x}

HISTFILE=$ZSTATEDIR/history
HISTSIZE=1000
SAVEHIST=100000
setopt inc_append_history
setopt extended_history

# with multios set, redirecting output does not prevent it from being piped
#   eg `echo hello >/dev/null | wc -l` evals to 1 (whereas unset, evals to 0)
# unsetopt multios

# don't error on wildcard no matches
setopt no_nomatch
unsetopt beep

bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle :compinstall filename '/home/david/.zshrc'

autoload -Uz compinit
compinit -d $ZCACHEDIR/zcompdump-$ZSH_VERSION
# End of lines added by compinstall

alias pw='read -s PASS; echo $PASS | sha256sum | hex2ascii'

# editor
export EDITOR=nvim
alias suvim='sudo -E nvim'
alias vim='nvim'

# code
alias g=git

# system
alias hdmi+='xrandr --output HDMI1 --auto --above eDP1'
alias hdmi+mirror='xrandr --output HDMI1 --auto --same-as eDP1 --scale-from 1920x1080'
alias hdmi-='xrandr --output HDMI1 --off'
alias red='redshift'
alias showdrivers='lspci -v'
alias syncclock='sudo ntpd -qg && sudo hwclock --systohc'
alias swapesc='setxkbmap -option caps:swapescape'
findsyms () {
  readonly local f="$1"
  readonly local d="$2"
  find -L $d -samefile $f 2&>/dev/null
}

# packages
pacman-cheatsheet () {
  # there's definitely a better way to do a multi-line string like this.
  # but I'm too lazy to look for it
  print "pacman cheatsheet"
  print "    pacman -Qs <regex>                      -- search installed packages"
  print "    pacman -Qeq                             -- list explicitly installed packages"
  print "    pacman -Qe                              -- list explicitly installed packages with version number"
  print "    pacman -Qent                            -- list explicitly installed native packages that are not direct or optional dependencies"
  print "    pacman -Qd                              -- list packages installed as dependencies"
  print "    pacman -Qdt                             -- list orphan dependencies"
  print "    pacman -Qtdq | pacman -Rns -            -- recursively remove orphans and their config files"
  print "    pacman -Ss <regex>                      -- search all packages"
  print "    pacman -Q --info <pkg>                  -- info on installed package"
  print "    pacman -S --info <pkg>                  -- info on any package"
  print "    pacman -Rs <pkg>                        -- remove package and any dangling dependencies"
  print "    pacman -D --asexplicit <pkgs>           -- mark packages explicitly installed"
  print "    pacman -D --asdeps <pkgs>               -- mark packages installed as dependencies"
  print
  print "    pkgfile <command>                       -- search packages providing command"
}
alias makepkg-rebuild='makepkg -fi'
alias initpkgsums='makepkg -g >> PKGBUILD'

# screenshots
alias lastscreen='ls ~/ss/*.png | tail -n 1'
alias vlastscreen='feh "$(ls ~/ss/*.png | tail -n 1)"'
alias screenfetch='screenfetch -c 04,13'
alias scrot='scrot ~/ss/%Y-%m-%dT%H%M%S%z.png'
screengrab() {
  readonly local filename="$(date +%Y-%m-%dT%H%M%S%z)"
  readonly local resolution='1920x1080' # '2560x1440'
  ffmpeg -f x11grab -s $resolution -r 60 -i :0.0 -q:v 0 -vcodec huffyuv ~/ss/${filename}.mkv
  ffmpeg -threads 8 -i ~/ss/${filename}.mkv -crf 10 -b:v 3M ~/ss/${filename}.webm
}

# media
alias chmodgw='sudo chmod -R ugo+rwX,o-w'
alias media='cd /mnt/media'
#alias ncmpcpp='ncmpcpp -h valhalla'
alias mpv='mpv -fs'

# gaming
alias steamdep='ldd ~/.local/share/Steam/ubuntu12_32/steamclient.so'
export STEAM_RUNTIME=0

# network
alias rsync='rsync -a --info=progress2'
alias svarog='ssh svarog'
alias valhalla='ssh valhalla'

# shell
setopt auto_cd
alias .='ls'

source "$ZDOTDIR"/colorsenv
export PS1="@%m %1~ $ "
source /usr/share/doc/pkgfile/command-not-found.zsh

alias ls='ls -h --color=auto -N'
alias which='which -a'

alias copy='xsel -i'
# diff
#   -a  treat all files as text
#   -u  output context
#   -r  recursively compare subdirectories
alias diff='diff -aur --color=always'

alias font++="printf '\33]50;%s\007' \"xft:Inconsolata LGC:style=Bold:pixelsize=20:antialias=true:hinting=true\""
alias font+="printf '\33]50;%s\007' \"xft:Inconsolata LGC:style=Bold:pixelsize=16:antialias=true:hinting=true\""
alias font="printf '\33]50;%s\007' \"xft:Inconsolata LGC:style=Bold:pixelsize=12:antialias=true:hinting=true\""
alias font-="printf '\33]50;%s\007' \"xft:Inconsolata LGC:style=Bold:pixelsize=10:antialias=true:hinting=true\""

# colored less output
export LESS='-R --use-color'
# Colored man pages: http://linuxtidbits.wordpress.com/2009/03/23/less-colors-for-man-pages/
# Less Colors for Man Pages
# TODO: this might not do anything
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;016m\E[48;5;220m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

# 4chan-compatible webm
### usage: webm -i INPUT -o OUTPUT -s START -d DURATION
###             [-w WIDTH] [-q QUALITY] [-t]
### START and DURATION must be a time duration
#            specification, see the Time duration
#            section in the ffmpeg-utils(1) manual.
webm() {
    while getopts ":i:o:w:q:s:d:t" opt; do
      case $opt in
        i) input="$OPTARG" ;;
        o) output="$OPTARG" ;;
        w) width="$OPTARG" ;;
        q) quality="$OPTARG" ;;
        s) start="$OPTARG" ;;
        d) duration="$OPTARG" ;;
        t) subtitles=true ;;
        :)  echo "Missing argument -$OPTARG" >&2
            exit 1 ;;
        \?) echo "Invalid option -$OPTARG" >&2
            exit 1
      esac
    done

    if [ -z "$input" ]; then
        printf "Required input parameter -i not given\n"
        return
    fi

    if [ -z "$output" ]; then
        printf "Required output parameter -o not given\n"
        return
    fi

    if [ -z "$start" ]; then
        printf "Required start time parameter -s not given\n"
        return
    fi

    if [ -z "$duration" ]; then
        printf "Required duration parameter -e not given\n"
        return
    fi

    if [ "$subtitles" ]; then
        subtitles_opts="-vf subtitles=$input"
    fi

    if [ -z "$width" ]; then
        width=960
    fi

    ffmpeg_str="ffmpeg -threads 8 -i $input -codec:v libvpx -vf scale=$width:-1 -crf 10 -b:v 3M -ss $start -t $duration -an -sn $subtitles_opts $output"
    eval "$ffmpeg_str"
    # TODO: add filesize check, repeat if unsatisfactory
}
