#!/usr/bin/env zsh
#
# docs/systemd-services
#
# enables and starts systemd services
#
services=(
          sshd.service
          systemd-swap.service
          reflector.service
          reflector.timer
          remote-fs.service
        )
for service in "$services[@]"; do
  systemctl enable $service
  systemctl start $service
done
